import { Image, Share, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import * as FileSystem from "expo-file-system/legacy";
import * as MediaLibrary from "expo-media-library";

interface Props {
  sourceUri: string;
  resultUri: string | null;
  provider?: string;
}

export function ImagePreview({ sourceUri, resultUri, provider }: Props) {
  async function saveImage() {
    if (!resultUri) {
      return;
    }

    const { status } = await MediaLibrary.requestPermissionsAsync();
    if (status !== "granted") {
      return;
    }

    await MediaLibrary.saveToLibraryAsync(resultUri);
    alert("Saved to gallery!");
  }

  async function shareImage() {
    if (!resultUri) {
      return;
    }

    const shareUri = `${FileSystem.cacheDirectory}clipart_share.jpg`;
    const base64 = await FileSystem.readAsStringAsync(resultUri, {
      encoding: FileSystem.EncodingType.Base64,
    });

    await FileSystem.writeAsStringAsync(shareUri, base64, {
      encoding: FileSystem.EncodingType.Base64,
    });

    await Share.share({ url: shareUri });
  }

  return (
    <View style={styles.container}>
      <View style={styles.row}>
        <View style={styles.imageBox}>
          <Text style={styles.label}>Original</Text>
          <Image source={{ uri: sourceUri }} style={styles.image} />
        </View>
        {resultUri ? (
          <View style={styles.imageBox}>
            <Text style={styles.label}>Result</Text>
            <Image source={{ uri: resultUri }} style={styles.image} />
          </View>
        ) : null}
      </View>

      {provider ? <Text style={styles.badge}>Generated by {provider}</Text> : null}

      {resultUri ? (
        <View style={styles.actions}>
          <TouchableOpacity style={styles.btn} onPress={saveImage}>
            <Text style={styles.btnText}>Save</Text>
          </TouchableOpacity>
          <TouchableOpacity style={[styles.btn, styles.btnAlt]} onPress={shareImage}>
            <Text style={styles.btnText}>Share</Text>
          </TouchableOpacity>
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    gap: 16,
  },
  row: {
    flexDirection: "row",
    gap: 12,
  },
  imageBox: {
    flex: 1,
    gap: 6,
  },
  label: {
    color: "#aaa",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  image: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: "#1a1a1a",
  },
  badge: {
    textAlign: "center",
    color: "#555",
    fontSize: 11,
  },
  actions: {
    flexDirection: "row",
    gap: 12,
  },
  btn: {
    flex: 1,
    backgroundColor: "#222",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  btnAlt: {
    backgroundColor: "#1a1a2e",
  },
  btnText: {
    color: "#fff",
    fontWeight: "600",
  },
});

